//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Util.Nacar {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class eesStateActions : global::System.Configuration.ApplicationSettingsBase {
        
        private static eesStateActions defaultInstance = ((eesStateActions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new eesStateActions())));
        
        public static eesStateActions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1064")]
        public int CAPTURA_EXPEDIENTE_PARA_PRESTAMOS_CONTROLLER_VERIFICACION {
            get {
                return ((int)(this["CAPTURA_EXPEDIENTE_PARA_PRESTAMOS_CONTROLLER_VERIFICACION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1065")]
        public int PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_CONSULTA_EQUIFAX {
            get {
                return ((int)(this["PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_CONSULTA_EQUIFAX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1066")]
        public int PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_ACTUALIZA_SCS {
            get {
                return ((int)(this["PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1067")]
        public int PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR {
            get {
                return ((int)(this["PRESTAMOS_CONTROLLER_VERIFICACION_PARA_PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1068")]
        public int PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR {
            get {
                return ((int)(this["PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1069")]
        public int PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR_PARA_PRESTAMOS_ACTUALIZA_SCS {
            get {
                return ((int)(this["PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR_PARA_PRESTAMOS_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1070")]
        public int PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_MESA_DE_CONTROL {
            get {
                return ((int)(this["PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1071")]
        public int PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR_PARA_PRESTAMOS_MESA_DE_CONTROL {
            get {
                return ((int)(this["PRESTAMOS_CONTROLLER__APROBACIÓN_NACAR_PARA_PRESTAMOS_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1072")]
        public int PRESTAMOS_ACTUALIZA_SCS_PARA_PRESTAMOS_CONTROLLER_DEVUELTO {
            get {
                return ((int)(this["PRESTAMOS_ACTUALIZA_SCS_PARA_PRESTAMOS_CONTROLLER_DEVUELTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1073")]
        public int PRESTAMOS_ACTUALIZA_SCS_PARA_ESTADO_RESPONSABLE_POR_EL_INFORME_DE_LOS_DATOS_CUADERNILLO_Y_SCORING_PARA_PRESTAMOS {
            get {
                return ((int)(this["PRESTAMOS_ACTUALIZA_SCS_PARA_ESTADO_RESPONSABLE_POR_EL_INFORME_DE_LOS_DATOS_CUADE" +
                    "RNILLO_Y_SCORING_PARA_PRESTAMOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1074")]
        public int ESTADO_RESPONSABLE_POR_EL_INFORME_DE_LOS_DATOS_CUADERNILLO_Y_SCORING_PARA_PRESTAMOS_PARA_PRESTAMOS_FORMALIZACION_NACAR {
            get {
                return ((int)(this["ESTADO_RESPONSABLE_POR_EL_INFORME_DE_LOS_DATOS_CUADERNILLO_Y_SCORING_PARA_PRESTAM" +
                    "OS_PARA_PRESTAMOS_FORMALIZACION_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1075")]
        public int PRESTAMOS_FORMALIZACION_NACAR_PARA_PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS {
            get {
                return ((int)(this["PRESTAMOS_FORMALIZACION_NACAR_PARA_PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1076")]
        public int PRESTAMOS_FORMALIZACION_NACAR_PARA_PRESTAMOS_MESA_DE_CONTROL {
            get {
                return ((int)(this["PRESTAMOS_FORMALIZACION_NACAR_PARA_PRESTAMOS_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1077")]
        public int PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS_PARA_TICKETS_FINALIZADOS {
            get {
                return ((int)(this["PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS_PARA_TICKETS_FINALIZADOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1078")]
        public int PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS_PARA_PRESTAMOS_MESA_DE_CONTROL {
            get {
                return ((int)(this["PRESTAMOS_FORMALIZACION_ACTUALIZAR_SCS_PARA_PRESTAMOS_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1079")]
        public int PRESTAMOS_ACTUALIZA_SCS_PARA_PRESTAMOS_MESA_DE_CONTROL {
            get {
                return ((int)(this["PRESTAMOS_ACTUALIZA_SCS_PARA_PRESTAMOS_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public int TARJETA_CAPTURA_EXPEDIENTE_PARA_TARJETA_CONTROLLER_VERIFICACIÓN {
            get {
                return ((int)(this["TARJETA_CAPTURA_EXPEDIENTE_PARA_TARJETA_CONTROLLER_VERIFICACIÓN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1081")]
        public int TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_CONSULTA_EQUIFAX {
            get {
                return ((int)(this["TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_CONSULTA_EQUIFAX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1082")]
        public int TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_APROBACIÓN_NACAR {
            get {
                return ((int)(this["TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_APROBACIÓN_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1083")]
        public int TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS {
            get {
                return ((int)(this["TARJETA_CONTROLLER_VERIFICACIÓN_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1084")]
        public int TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_CONTROLLER_APROBACIÓN_NACAR {
            get {
                return ((int)(this["TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_CONTROLLER_APROBACIÓN_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1085")]
        public int TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_MESA_DE_CONTROL {
            get {
                return ((int)(this["TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1086")]
        public int TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_CONTROLLER_DEVUELTO {
            get {
                return ((int)(this["TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_CONTROLLER_DEVUELTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1087")]
        public int TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_FORMALIZACION_INFORMA_DATOS_CUADERNILO_Y_SCORING {
            get {
                return ((int)(this["TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_FORMALIZACION_INFORMA_DATOS_CUADERN" +
                    "ILO_Y_SCORING"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1088")]
        public int TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_MESA_DE_CONTROL {
            get {
                return ((int)(this["TARJETA_CONTROLLER_ACTUALIZA_SCS_PARA_TARJETA_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1089")]
        public int TARJETA_CONTROLLER_APROBACIÓN_NACAR_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS {
            get {
                return ((int)(this["TARJETA_CONTROLLER_APROBACIÓN_NACAR_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1090")]
        public int TARJETA_CONTROLLER_APROBACIÓN_NACAR_PARA_TARJETA_MESA_DE_CONTROL {
            get {
                return ((int)(this["TARJETA_CONTROLLER_APROBACIÓN_NACAR_PARA_TARJETA_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1091")]
        public int TARJETA_FORMALIZACION_INFORMA_DATOS_CUADERNILO_Y_SCORING_PARA_TARJETA_FORMALIZACION_NACAR {
            get {
                return ((int)(this["TARJETA_FORMALIZACION_INFORMA_DATOS_CUADERNILO_Y_SCORING_PARA_TARJETA_FORMALIZACI" +
                    "ON_NACAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1092")]
        public int TARJETA_FORMALIZACION_NACAR_PARA_TARJETA_FORMALIZACION_ACTUALIZAR_SCS {
            get {
                return ((int)(this["TARJETA_FORMALIZACION_NACAR_PARA_TARJETA_FORMALIZACION_ACTUALIZAR_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1093")]
        public int TARJETA_FORMALIZACION_NACAR_PARA_TARJETA_MESA_DE_CONTROL {
            get {
                return ((int)(this["TARJETA_FORMALIZACION_NACAR_PARA_TARJETA_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1094")]
        public int TARJETA_FORMALIZACION_ACTUALIZAR_SCS_PARA_TARJETA_FINALIZADO {
            get {
                return ((int)(this["TARJETA_FORMALIZACION_ACTUALIZAR_SCS_PARA_TARJETA_FINALIZADO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1095")]
        public int TARJETA_FORMALIZACION_ACTUALIZAR_SCS_PARA_TARJETA_MESA_DE_CONTROL {
            get {
                return ((int)(this["TARJETA_FORMALIZACION_ACTUALIZAR_SCS_PARA_TARJETA_MESA_DE_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1096")]
        public int PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_ACTUALIZA_SCS {
            get {
                return ((int)(this["PRESTAMOS_CONSULTA_EQUIFAX_PARA_PRESTAMOS_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1097")]
        public int TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS {
            get {
                return ((int)(this["TARJETA_CONTROLLER_CONSULTA_EQUIFAX_PARA_TARJETA_CONTROLLER_ACTUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1104")]
        public int TARJETA_MESA_VALIDA_RIESGO_CONJUGUE_PARA_TARJETA_MESA_ATUALIZA_SCS {
            get {
                return ((int)(this["TARJETA_MESA_VALIDA_RIESGO_CONJUGUE_PARA_TARJETA_MESA_ATUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1108")]
        public int TARJETA_MESA_VALIDA_RIESGO_CONJUGUE_PARA_MESA_MESA_DE_CORRECAO {
            get {
                return ((int)(this["TARJETA_MESA_VALIDA_RIESGO_CONJUGUE_PARA_MESA_MESA_DE_CORRECAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1123")]
        public int PRESTAMO_MESA_VALIDA_RIESGO_CONJUGUE_PARA_PRESTAMO_MESA_ATUALIZA_SCS {
            get {
                return ((int)(this["PRESTAMO_MESA_VALIDA_RIESGO_CONJUGUE_PARA_PRESTAMO_MESA_ATUALIZA_SCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1124")]
        public int PRESTAMO_MESA_VALIDA_RIESGO_CONJUGUE_PARA_MESA_MESA_DE_CORRECAO {
            get {
                return ((int)(this["PRESTAMO_MESA_VALIDA_RIESGO_CONJUGUE_PARA_MESA_MESA_DE_CORRECAO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1100")]
        public int VALIDACION_3270_TARJETA_PARA_VENTANA_VALIDACION_TARJETA {
            get {
                return ((int)(this["VALIDACION_3270_TARJETA_PARA_VENTANA_VALIDACION_TARJETA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1099")]
        public int VALIDACION_3270_TARJETA_PARRA_VENTANA_CORRECION_MESA_CONTROL {
            get {
                return ((int)(this["VALIDACION_3270_TARJETA_PARRA_VENTANA_CORRECION_MESA_CONTROL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1152")]
        public int ROBOT_CAPTURA_DE_PAGOS_TARJETA_PARA_EVALUAR_DATOS_SCS_TARJETAS {
            get {
                return ((int)(this["ROBOT_CAPTURA_DE_PAGOS_TARJETA_PARA_EVALUAR_DATOS_SCS_TARJETAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1153")]
        public int ROBOT_CAPTURA_DE_PAGOS_TARJETA_PARA_MESA_DE_CORRECCION_TARJETAS {
            get {
                return ((int)(this["ROBOT_CAPTURA_DE_PAGOS_TARJETA_PARA_MESA_DE_CORRECCION_TARJETAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1151")]
        public int ROBOT_CAPTURA_DE_PAGOS_PRESTAMO_PARA_EVALUAR_DATOS_SCS_PRESTAMOS {
            get {
                return ((int)(this["ROBOT_CAPTURA_DE_PAGOS_PRESTAMO_PARA_EVALUAR_DATOS_SCS_PRESTAMOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1243")]
        public int ROBOT_CAPTURA_DE_PAGOS_PRESTAMO_PARA_MESA_DE_CORRECCION_PRESTAMOS {
            get {
                return ((int)(this["ROBOT_CAPTURA_DE_PAGOS_PRESTAMO_PARA_MESA_DE_CORRECCION_PRESTAMOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1322")]
        public int MC_TARJETA_DEVUELTO_PARA_VALID_3270 {
            get {
                return ((int)(this["MC_TARJETA_DEVUELTO_PARA_VALID_3270"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1314")]
        public int MC_TARJETA_CAPT_EXP_PARA_MESA_CORRECCION {
            get {
                return ((int)(this["MC_TARJETA_CAPT_EXP_PARA_MESA_CORRECCION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1321")]
        public int MC_PRESTAMO_DEVUELTO_PARA_VALID_3270 {
            get {
                return ((int)(this["MC_PRESTAMO_DEVUELTO_PARA_VALID_3270"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1315")]
        public int MC_PRESTAMO_CAPT_EXP_PARA_MESA_CORRECCION {
            get {
                return ((int)(this["MC_PRESTAMO_CAPT_EXP_PARA_MESA_CORRECCION"]));
            }
        }
    }
}
